//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EletrocaoMauiApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EletrocaoMauiApp.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tempo médio de atraso dos comandos do robô:.
        /// </summary>
        public static string ATRASO_MEDIO_ROBO {
            get {
                return ResourceManager.GetString("ATRASO_MEDIO_ROBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tempo médio de atraso dos comandos do simulador:.
        /// </summary>
        public static string ATRASO_MEDIO_SIMULADOR {
            get {
                return ResourceManager.GetString("ATRASO_MEDIO_SIMULADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a caminharfrente.png.
        /// </summary>
        public static string CAMINHAR_IMG {
            get {
                return ResourceManager.GetString("CAMINHAR_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a caminhartras.png.
        /// </summary>
        public static string CAMINHAR_TRAS_IMG {
            get {
                return ResourceManager.GetString("CAMINHAR_TRAS_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conectado.
        /// </summary>
        public static string CONECTADO {
            get {
                return ResourceManager.GetString("CONECTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conectar.
        /// </summary>
        public static string CONECTAR {
            get {
                return ResourceManager.GetString("CONECTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conectar ao simulador.
        /// </summary>
        public static string CONECTAR_SIMULADOR {
            get {
                return ResourceManager.GetString("CONECTAR_SIMULADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurar movimentos.
        /// </summary>
        public static string CONFIGURAR_MOVIMENTOS {
            get {
                return ResourceManager.GetString("CONFIGURAR_MOVIMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corrente na bateria.
        /// </summary>
        public static string CORRENTE_BATERIA {
            get {
                return ResourceManager.GetString("CORRENTE_BATERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Corrente (mA).
        /// </summary>
        public static string CORRENTE_MA {
            get {
                return ResourceManager.GetString("CORRENTE_MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a deitar.png.
        /// </summary>
        public static string DEITAR_IMG {
            get {
                return ResourceManager.GetString("DEITAR_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desconectado.
        /// </summary>
        public static string DESCONECTADO {
            get {
                return ResourceManager.GetString("DESCONECTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desvio padrão do robô:.
        /// </summary>
        public static string DESVIO_PADRAO_ROBO {
            get {
                return ResourceManager.GetString("DESVIO_PADRAO_ROBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desvio padrão do simulador:.
        /// </summary>
        public static string DESVIO_PADRAO_SIMULADOR {
            get {
                return ResourceManager.GetString("DESVIO_PADRAO_SIMULADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estado do robô:.
        /// </summary>
        public static string ESTADO_ROBO {
            get {
                return ResourceManager.GetString("ESTADO_ROBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a girardireita.png.
        /// </summary>
        public static string GIRAR_DIREITA_IMG {
            get {
                return ResourceManager.GetString("GIRAR_DIREITA_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a giraresquerda.png.
        /// </summary>
        public static string GIRAR_ESQUERDA_IMG {
            get {
                return ResourceManager.GetString("GIRAR_ESQUERDA_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informações do robô.
        /// </summary>
        public static string INFORMACOES_ROBO {
            get {
                return ResourceManager.GetString("INFORMACOES_ROBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a levantar.png.
        /// </summary>
        public static string LEVANTAR_IMG {
            get {
                return ResourceManager.GetString("LEVANTAR_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a levantarpata.png.
        /// </summary>
        public static string LEVANTAR_PATA_IMG {
            get {
                return ResourceManager.GetString("LEVANTAR_PATA_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mensagens perdidas:.
        /// </summary>
        public static string MENSAGENS_PERDIDAS {
            get {
                return ResourceManager.GetString("MENSAGENS_PERDIDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mensagens recebidas:.
        /// </summary>
        public static string MENSAGENS_RECEBIDAS {
            get {
                return ResourceManager.GetString("MENSAGENS_RECEBIDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tensão da bateria do microcontrolador.
        /// </summary>
        public static string MICRO_VOLTAGE {
            get {
                return ResourceManager.GetString("MICRO_VOLTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Robô:.
        /// </summary>
        public static string ROBO {
            get {
                return ResourceManager.GetString("ROBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar usuário e senha.
        /// </summary>
        public static string SALVA_USUARIO_SENHA {
            get {
                return ResourceManager.GetString("SALVA_USUARIO_SENHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a sentar.png.
        /// </summary>
        public static string SENTAR_IMG {
            get {
                return ResourceManager.GetString("SENTAR_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tensão da bateria dos servomotores.
        /// </summary>
        public static string SERVO_VOLTAGE {
            get {
                return ResourceManager.GetString("SERVO_VOLTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Simulador:.
        /// </summary>
        public static string SIMULADOR {
            get {
                return ResourceManager.GetString("SIMULADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Taxa de recebimento:.
        /// </summary>
        public static string TAXA_RECEBIMENTO {
            get {
                return ResourceManager.GetString("TAXA_RECEBIMENTO", resourceCulture);
            }
        }
    }
}
